spring:
    #db  -- 默认数据源
    datasource:
        #本地开发
        url: jdbc:mysql://127.0.0.1:3306/netty-chat?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        
#mybatis                         
mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml 
    
logging: 
    level: 
        zqit: debug
        tk.mybatis.springboot.mapper: debug