server:
    #端口
    port: 9030
    context-path: /NETTY-CHAT-echoServer
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/

netty:
    port: 8888
    url: 127.0.0.1   
        
#redis       
spring:
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
        timeout: 10000