server:
    #端口
    port: 8900
    context-path: /NETTY-CHAT-MQ-LISTENER
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
            
            
spring:
    #activemq
    activemq:
        user: admin    # 连接用户名
        password: admin   # 连接密码
        broker-url: tcp://zhuoqin-test.cn:61616 # 消息组件的连接主机信息
        pool:
            enabled: true
            max-connections: 10